import Link from 'next/link';
import { requireRole } from '@/lib/auth/guard';
import { adminDb } from '@/lib/database/admin';
import { MetricCard, PageTitle, Panel, StatusPill } from '@/components/dashboard';
import { ModelKillSwitch } from '@/components/teacher/model-kill-switch';
import { PRIMARY, TIER } from '@/lib/orcarouter/routers';
import { formatDateTime, formatUsd } from '@/lib/shared/format';

export default async function OpsPage() {
  const context = await requireRole('teacher','admin'); const db=adminDb();
  const [runs, disabled, guards] = await Promise.all([db.from('agent_runs').select('*').eq('tenant_id',context.tenantId).order('created_at',{ascending:false}).limit(100),db.from('model_disables').select('*').eq('tenant_id',context.tenantId).is('released_at',null),db.from('guard_events').select('id',{count:'exact',head:true}).eq('tenant_id',context.tenantId)]);
  const rows=runs.data??[]; const cost=rows.reduce((s,r)=>s+Number(r.estimated_cost_usd??0),0); const latency=rows.length?Math.round(rows.reduce((s,r)=>s+(r.latency_ms??0),0)/rows.length):0; const primary=PRIMARY[TIER].studentChat; const isDisabled=(disabled.data??[]).some(v=>v.model===primary);
  return <div><PageTitle eyebrow="AI Operations" title="AI運用" description="実際に選ばれたモデル、費用、遅延、フォールバック、安全性遮断を確認できます。" action={context.role==='admin'?<ModelKillSwitch model={primary} initiallyDisabled={isDisabled}/>:undefined}/><div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><MetricCard label="実行数（直近）" value={rows.length}/><MetricCard label="費用" value={formatUsd(cost)} tone="slate"/><MetricCard label="平均遅延" value={`${latency}ms`} tone="slate"/><MetricCard label="安全性遮断" value={guards.count??0} tone={(guards.count??0)?'rose':'emerald'}/></div><div className="mt-6 grid gap-6 xl:grid-cols-[1fr_280px]"><Panel title="実行履歴" action={<Link href="/teacher/ops/security" className="text-xs font-bold text-emerald-700">安全性ログ</Link>}><div className="overflow-x-auto"><table className="w-full min-w-[720px] text-left text-sm"><thead className="text-xs text-slate-500"><tr><th className="pb-3">日時</th><th>Agent</th><th>モデル</th><th>状態</th><th>遅延</th><th>費用</th></tr></thead><tbody className="divide-y divide-slate-100">{rows.map(run=><tr key={run.id}><td className="py-3">{formatDateTime(run.created_at)}</td><td><Link href={`/teacher/ops/runs/${run.id}`} className="font-bold text-emerald-700">{run.agent_name}</Link></td><td className="max-w-52 truncate">{run.resolved_model??'—'}</td><td><StatusPill tone={run.status==='ok'?'emerald':run.status==='blocked'||run.status==='error'?'rose':'amber'}>{run.status}</StatusPill></td><td>{run.latency_ms??0}ms</td><td>{formatUsd(Number(run.estimated_cost_usd??0))}</td></tr>)}</tbody></table></div></Panel><Panel title="ルーティング"><p className="text-xs font-bold uppercase tracking-wide text-slate-500">現在の階層</p><p className="mt-2 text-lg font-bold">{TIER==='production'?'本番モデル':'開発モデル'}</p><p className="mt-4 break-all rounded-lg bg-slate-50 p-3 text-xs">{primary}</p><div className="mt-4"><StatusPill tone={isDisabled?'rose':'emerald'}>{isDisabled?'停止中':'稼働中'}</StatusPill></div></Panel></div></div>;
}
